####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-flowexperimental
Description: Simulators and utilities for automatic differentiation
Version: 2025.04-pre
Label: 2025.04-pre
Maintainer: xxxx
MaintainerName:xxxx
Url: http://opm-project.org
Depends: dune-istl (>= 2.8) opm-common opm-grid opm-simulators
